// generated by create_corlors.py

#[repr(u16)]
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Default)]
pub enum Colors {
    AliceBlue = 0xf7df,            // Rgb(240, 248, 255)
    AntiqueWhite = 0xff5a,         // Rgb(250, 235, 215)
    Aqua = 0x07fe,                 // Rgb(0, 255, 255)
    Aquamarine = 0x7ffa,           // Rgb(127, 255, 212)
    Azure = 0xf7ff,                // Rgb(240, 255, 255)
    Beige = 0xf7bb,                // Rgb(245, 245, 220)
    Bisque = 0xff38,               // Rgb(255, 228, 196)
    Black = 0x0000,                // Rgb(0, 0, 0)
    BlanchedAlmond = 0xff59,       // Rgb(255, 235, 205)
    Blue = 0x001f,                 // Rgb(0, 0, 255)
    BlueViolet = 0x895c,           // Rgb(138, 43, 226)
    Brown = 0xa145,                // Rgb(165, 42, 42)
    BurlyWood = 0xddd0,            // Rgb(222, 184, 135)
    CadetBlue = 0x5cf4,            // Rgb(95, 158, 160)
    Chartreuse = 0x7fe1,           // Rgb(127, 255, 0)
    Chocolate = 0xd343,            // Rgb(210, 105, 30)
    Coral = 0xfbea,                // Rgb(255, 127, 80)
    CornflowerBlue = 0x64bd,       // Rgb(100, 149, 237)
    Cornsilk = 0xffdb,             // Rgb(255, 248, 220)
    Crimson = 0xd8a7,              // Rgb(220, 20, 60)
    Cyan = 0x07ff,                 // Rgb(0, 255, 255)
    DarkBlue = 0x0011,             // Rgb(0, 0, 139)
    DarkCyan = 0x0451,             // Rgb(0, 139, 139)
    DarkGoldenrod = 0xbc21,        // Rgb(184, 134, 11)
    DarkGray = 0xad55,             // Rgb(169, 169, 169)
    DarkGreen = 0x0320,            // Rgb(0, 100, 0)
    DarkKhaki = 0xbdad,            // Rgb(189, 183, 107)
    DarkMagenta = 0x8811,          // Rgb(139, 0, 139)
    DarkOliveGreen = 0x5345,       // Rgb(85, 107, 47)
    DarkOrange = 0xfc60,           // Rgb(255, 140, 0)
    DarkOrchid = 0x9999,           // Rgb(153, 50, 204)
    DarkRed = 0x8800,              // Rgb(139, 0, 0)
    DarkSalmon = 0xecaf,           // Rgb(233, 150, 122)
    DarkSeaGreen = 0x8df1,         // Rgb(143, 188, 143)
    DarkSlateBlue = 0x49f1,        // Rgb(72, 61, 139)
    DarkSlateGray = 0x2a69,        // Rgb(47, 79, 79)
    DarkTurquoise = 0x067a,        // Rgb(0, 206, 209)
    DarkViolet = 0x901a,           // Rgb(148, 0, 211)
    DeepPink = 0xf8b2,             // Rgb(255, 20, 147)
    DeepSkyBlue = 0x05ff,          // Rgb(0, 191, 255)
    DimGray = 0x6b4d,              // Rgb(105, 105, 105)
    DodgerBlue = 0x1c9f,           // Rgb(30, 144, 255)
    FireBrick = 0xb104,            // Rgb(178, 34, 34)
    FloralWhite = 0xffde,          // Rgb(255, 250, 240)
    ForestGreen = 0x2444,          // Rgb(34, 139, 34)
    Gainsboro = 0xdefb,            // Rgb(220, 220, 220)
    GhostWhite = 0xffbf,           // Rgb(248, 248, 255)
    Gold = 0xfea0,                 // Rgb(255, 215, 0)
    Goldenrod = 0xdd24,            // Rgb(218, 165, 32)
    Gray = 0x8410,                 // Rgb(128, 128, 128)
    Green = 0x0400,                // Rgb(0, 128, 0)
    GreenYellow = 0xafe5,          // Rgb(173, 255, 47)
    Honeydew = 0xf7fe,             // Rgb(240, 255, 240)
    HotPink = 0xfb56,              // Rgb(255, 105, 180)
    IndianRed = 0xcaeb,            // Rgb(205, 92, 92)
    Indigo = 0x4810,               // Rgb(75, 0, 130)
    Ivory = 0xfffe,                // Rgb(255, 255, 240)
    Khaki = 0xf731,                // Rgb(240, 230, 140)
    Lavender = 0xe73f,             // Rgb(230, 230, 250)
    LavenderBlush = 0xff9e,        // Rgb(255, 240, 245)
    LawnGreen = 0x7fe0,            // Rgb(124, 252, 0)
    LemonChiffon = 0xffd9,         // Rgb(255, 250, 205)
    LightBlue = 0xaedc,            // Rgb(173, 216, 230)
    LightCoral = 0xf410,           // Rgb(240, 128, 128)
    LightCyan = 0xe7ff,            // Rgb(224, 255, 255)
    LightGoldenrodYellow = 0xffda, // Rgb(250, 250, 210)
    LightGray = 0xd69a,            // Rgb(211, 211, 211)
    LightGreen = 0x9772,           // Rgb(144, 238, 144)
    LightPink = 0xfdb8,            // Rgb(255, 182, 193)
    LightSalmon = 0xfd0f,          // Rgb(255, 160, 122)
    LightSeaGreen = 0x2595,        // Rgb(32, 178, 170)
    LightSkyBlue = 0x867f,         // Rgb(135, 206, 250)
    LightSlateGray = 0x7453,       // Rgb(119, 136, 153)
    LightSteelBlue = 0xb63b,       // Rgb(176, 196, 222)
    LightYellow = 0xfffc,          // Rgb(255, 255, 224)
    Lime = 0x07e0,                 // Rgb(0, 255, 0)
    LimeGreen = 0x3666,            // Rgb(50, 205, 50)
    Linen = 0xff9c,                // Rgb(250, 240, 230)
    Magenta = 0xf81f,              // Rgb(255, 0, 255)
    Maroon = 0x8000,               // Rgb(128, 0, 0)
    MediumAquamarine = 0x6675,     // Rgb(102, 205, 170)
    MediumBlue = 0x0019,           // Rgb(0, 0, 205)
    MediumOrchid = 0xbaba,         // Rgb(186, 85, 211)
    MediumPurple = 0x939b,         // Rgb(147, 112, 219)
    MediumSeaGreen = 0x3d8e,       // Rgb(60, 179, 113)
    MediumSlateBlue = 0x7b5d,      // Rgb(123, 104, 238)
    MediumSpringGreen = 0x07d3,    // Rgb(0, 250, 154)
    MediumTurquoise = 0x4e99,      // Rgb(72, 209, 204)
    MediumVioletRed = 0xc0b0,      // Rgb(199, 21, 133)
    MidnightBlue = 0x18ce,         // Rgb(25, 25, 112)
    MintCream = 0xf7bf,            // Rgb(245, 255, 250)
    MistyRose = 0xff3c,            // Rgb(255, 228, 225)
    Moccasin = 0xff36,             // Rgb(255, 228, 181)
    NavajoWhite = 0xfef5,          // Rgb(255, 222, 173)
    Navy = 0x0010,                 // Rgb(0, 0, 128)
    OldLace = 0xffbc,              // Rgb(253, 245, 230)
    Olive = 0x8400,                // Rgb(128, 128, 0)
    OliveDrab = 0x6c64,            // Rgb(107, 142, 35)
    Orange = 0xfd20,               // Rgb(255, 165, 0)
    OrangeRed = 0xfa20,            // Rgb(255, 69, 0)
    Orchid = 0xdb9a,               // Rgb(218, 112, 214)
    PaleGoldenrod = 0xef55,        // Rgb(238, 232, 170)
    PaleGreen = 0x9fd3,            // Rgb(152, 251, 152)
    PaleTurquoise = 0xaf7d,        // Rgb(175, 238, 238)
    PaleVioletRed = 0xdb92,        // Rgb(219, 112, 147)
    PapayaWhip = 0xff7a,           // Rgb(255, 239, 213)
    PeachPuff = 0xfed7,            // Rgb(255, 218, 185)
    Peru = 0xcc27,                 // Rgb(205, 133, 63)
    Pink = 0xfe19,                 // Rgb(255, 192, 203)
    Plum = 0xdd1b,                 // Rgb(221, 160, 221)
    PowderBlue = 0xb71c,           // Rgb(176, 224, 230)
    Purple = 0x8010,               // Rgb(128, 0, 128)
    #[default]
    Red = 0xf800,    // Rgb(255, 0, 0)
    RosyBrown = 0xbc71,            // Rgb(188, 143, 143)
    RoyalBlue = 0x435c,            // Rgb(65, 105, 225)
    SaddleBrown = 0x8a22,          // Rgb(139, 69, 19)
    Salmon = 0xfc0e,               // Rgb(250, 128, 114)
    SandyBrown = 0xf52c,           // Rgb(244, 164, 96)
    SeaGreen = 0x2c4a,             // Rgb(46, 139, 87)
    Seashell = 0xffbd,             // Rgb(255, 245, 238)
    Sienna = 0xa285,               // Rgb(160, 82, 45)
    Silver = 0xc618,               // Rgb(192, 192, 192)
    SkyBlue = 0x867d,              // Rgb(135, 206, 235)
    SlateBlue = 0x6ad9,            // Rgb(106, 90, 205)
    SlateGray = 0x7412,            // Rgb(112, 128, 144)
    Snow = 0xffdf,                 // Rgb(255, 250, 250)
    SpringGreen = 0x07ef,          // Rgb(0, 255, 127)
    SteelBlue = 0x4416,            // Rgb(70, 130, 180)
    Tan = 0xd5b1,                  // Rgb(210, 180, 140)
    Teal = 0x0410,                 // Rgb(0, 128, 128)
    Thistle = 0xddfb,              // Rgb(216, 191, 216)
    Tomato = 0xfb08,               // Rgb(255, 99, 71)
    Turquoise = 0x471a,            // Rgb(64, 224, 208)
    Violet = 0xec1d,               // Rgb(238, 130, 238)
    Wheat = 0xf6f6,                // Rgb(245, 222, 179)
    White = 0xffff,                // Rgb(255, 255, 255)
    WhiteSmoke = 0xf7be,           // Rgb(245, 245, 245)
    Yellow = 0xffe0,               // Rgb(255, 255, 0)
    YellowGreen = 0x9e66,          // Rgb(154, 205, 50)
}

use embedded_graphics::pixelcolor::{raw::RawU16, PixelColor};

impl PixelColor for Colors {
    type Raw = RawU16;
}

impl From<Colors> for RawU16 {
    fn from(color: Colors) -> RawU16 {
        RawU16::new(color as u16)
    }
}

use embedded_graphics::pixelcolor::{Bgr888, BinaryColor, Rgb888};
use embedded_graphics::prelude::WebColors;

impl From<Bgr888> for Colors {
    fn from(_color: Bgr888) -> Self {
        Colors::White
    }
}

impl From<Rgb888> for Colors {
    fn from(_color: Rgb888) -> Self {
        Colors::White
    }
}

impl From<BinaryColor> for Colors {
    fn from(_: BinaryColor) -> Self {
        Colors::White
    }
}

impl Colors {
    pub unsafe fn from_u16_unchecked(color: u16) -> Colors {
        // Safety: Every u16 is a valid Color
        unsafe { core::mem::transmute::<u16, Colors>(color) }
    }
}

impl From<Colors> for Bgr888 {
    fn from(val: Colors) -> Self {
        match val {
            Colors::AliceBlue => Bgr888::CSS_ALICE_BLUE,
            Colors::AntiqueWhite => Bgr888::CSS_ANTIQUE_WHITE,
            Colors::Aqua => Bgr888::CSS_AQUA,
            Colors::Aquamarine => Bgr888::CSS_AQUAMARINE,
            Colors::Azure => Bgr888::CSS_AZURE,
            Colors::Beige => Bgr888::CSS_BEIGE,
            Colors::Bisque => Bgr888::CSS_BISQUE,
            Colors::Black => Bgr888::CSS_BLACK,
            Colors::BlanchedAlmond => Bgr888::CSS_BLANCHED_ALMOND,
            Colors::Blue => Bgr888::CSS_BLUE,
            Colors::BlueViolet => Bgr888::CSS_BLUE_VIOLET,
            Colors::Brown => Bgr888::CSS_BROWN,
            Colors::BurlyWood => Bgr888::CSS_BURLY_WOOD,
            Colors::CadetBlue => Bgr888::CSS_CADET_BLUE,
            Colors::Chartreuse => Bgr888::CSS_CHARTREUSE,
            Colors::Chocolate => Bgr888::CSS_CHOCOLATE,
            Colors::Coral => Bgr888::CSS_CORAL,
            Colors::CornflowerBlue => Bgr888::CSS_CORNFLOWER_BLUE,
            Colors::Cornsilk => Bgr888::CSS_CORNSILK,
            Colors::Crimson => Bgr888::CSS_CRIMSON,
            Colors::Cyan => Bgr888::CSS_CYAN,
            Colors::DarkBlue => Bgr888::CSS_DARK_BLUE,
            Colors::DarkCyan => Bgr888::CSS_DARK_CYAN,
            Colors::DarkGoldenrod => Bgr888::CSS_DARK_GOLDENROD,
            Colors::DarkGray => Bgr888::CSS_DARK_GRAY,
            Colors::DarkGreen => Bgr888::CSS_DARK_GREEN,
            Colors::DarkKhaki => Bgr888::CSS_DARK_KHAKI,
            Colors::DarkMagenta => Bgr888::CSS_DARK_MAGENTA,
            Colors::DarkOliveGreen => Bgr888::CSS_DARK_OLIVE_GREEN,
            Colors::DarkOrange => Bgr888::CSS_DARK_ORANGE,
            Colors::DarkOrchid => Bgr888::CSS_DARK_ORCHID,
            Colors::DarkRed => Bgr888::CSS_DARK_RED,
            Colors::DarkSalmon => Bgr888::CSS_DARK_SALMON,
            Colors::DarkSeaGreen => Bgr888::CSS_DARK_SEA_GREEN,
            Colors::DarkSlateBlue => Bgr888::CSS_DARK_SLATE_BLUE,
            Colors::DarkSlateGray => Bgr888::CSS_DARK_SLATE_GRAY,
            Colors::DarkTurquoise => Bgr888::CSS_DARK_TURQUOISE,
            Colors::DarkViolet => Bgr888::CSS_DARK_VIOLET,
            Colors::DeepPink => Bgr888::CSS_DEEP_PINK,
            Colors::DeepSkyBlue => Bgr888::CSS_DEEP_SKY_BLUE,
            Colors::DimGray => Bgr888::CSS_DIM_GRAY,
            Colors::DodgerBlue => Bgr888::CSS_DODGER_BLUE,
            Colors::FireBrick => Bgr888::CSS_FIRE_BRICK,
            Colors::FloralWhite => Bgr888::CSS_FLORAL_WHITE,
            Colors::ForestGreen => Bgr888::CSS_FOREST_GREEN,
            Colors::Gainsboro => Bgr888::CSS_GAINSBORO,
            Colors::GhostWhite => Bgr888::CSS_GHOST_WHITE,
            Colors::Gold => Bgr888::CSS_GOLD,
            Colors::Goldenrod => Bgr888::CSS_GOLDENROD,
            Colors::Gray => Bgr888::CSS_GRAY,
            Colors::Green => Bgr888::CSS_GREEN,
            Colors::GreenYellow => Bgr888::CSS_GREEN_YELLOW,
            Colors::Honeydew => Bgr888::CSS_HONEYDEW,
            Colors::HotPink => Bgr888::CSS_HOT_PINK,
            Colors::IndianRed => Bgr888::CSS_INDIAN_RED,
            Colors::Indigo => Bgr888::CSS_INDIGO,
            Colors::Ivory => Bgr888::CSS_IVORY,
            Colors::Khaki => Bgr888::CSS_KHAKI,
            Colors::Lavender => Bgr888::CSS_LAVENDER,
            Colors::LavenderBlush => Bgr888::CSS_LAVENDER_BLUSH,
            Colors::LawnGreen => Bgr888::CSS_LAWN_GREEN,
            Colors::LemonChiffon => Bgr888::CSS_LEMON_CHIFFON,
            Colors::LightBlue => Bgr888::CSS_LIGHT_BLUE,
            Colors::LightCoral => Bgr888::CSS_LIGHT_CORAL,
            Colors::LightCyan => Bgr888::CSS_LIGHT_CYAN,
            Colors::LightGoldenrodYellow => Bgr888::CSS_LIGHT_GOLDENROD_YELLOW,
            Colors::LightGray => Bgr888::CSS_LIGHT_GRAY,
            Colors::LightGreen => Bgr888::CSS_LIGHT_GREEN,
            Colors::LightPink => Bgr888::CSS_LIGHT_PINK,
            Colors::LightSalmon => Bgr888::CSS_LIGHT_SALMON,
            Colors::LightSeaGreen => Bgr888::CSS_LIGHT_SEA_GREEN,
            Colors::LightSkyBlue => Bgr888::CSS_LIGHT_SKY_BLUE,
            Colors::LightSlateGray => Bgr888::CSS_LIGHT_SLATE_GRAY,
            Colors::LightSteelBlue => Bgr888::CSS_LIGHT_STEEL_BLUE,
            Colors::LightYellow => Bgr888::CSS_LIGHT_YELLOW,
            Colors::Lime => Bgr888::CSS_LIME,
            Colors::LimeGreen => Bgr888::CSS_LIME_GREEN,
            Colors::Linen => Bgr888::CSS_LINEN,
            Colors::Magenta => Bgr888::CSS_MAGENTA,
            Colors::Maroon => Bgr888::CSS_MAROON,
            Colors::MediumAquamarine => Bgr888::CSS_MEDIUM_AQUAMARINE,
            Colors::MediumBlue => Bgr888::CSS_MEDIUM_BLUE,
            Colors::MediumOrchid => Bgr888::CSS_MEDIUM_ORCHID,
            Colors::MediumPurple => Bgr888::CSS_MEDIUM_PURPLE,
            Colors::MediumSeaGreen => Bgr888::CSS_MEDIUM_SEA_GREEN,
            Colors::MediumSlateBlue => Bgr888::CSS_MEDIUM_SLATE_BLUE,
            Colors::MediumSpringGreen => Bgr888::CSS_MEDIUM_SPRING_GREEN,
            Colors::MediumTurquoise => Bgr888::CSS_MEDIUM_TURQUOISE,
            Colors::MediumVioletRed => Bgr888::CSS_MEDIUM_VIOLET_RED,
            Colors::MidnightBlue => Bgr888::CSS_MIDNIGHT_BLUE,
            Colors::MintCream => Bgr888::CSS_MINT_CREAM,
            Colors::MistyRose => Bgr888::CSS_MISTY_ROSE,
            Colors::Moccasin => Bgr888::CSS_MOCCASIN,
            Colors::NavajoWhite => Bgr888::CSS_NAVAJO_WHITE,
            Colors::Navy => Bgr888::CSS_NAVY,
            Colors::OldLace => Bgr888::CSS_OLD_LACE,
            Colors::Olive => Bgr888::CSS_OLIVE,
            Colors::OliveDrab => Bgr888::CSS_OLIVE_DRAB,
            Colors::Orange => Bgr888::CSS_ORANGE,
            Colors::OrangeRed => Bgr888::CSS_ORANGE_RED,
            Colors::Orchid => Bgr888::CSS_ORCHID,
            Colors::PaleGoldenrod => Bgr888::CSS_PALE_GOLDENROD,
            Colors::PaleGreen => Bgr888::CSS_PALE_GREEN,
            Colors::PaleTurquoise => Bgr888::CSS_PALE_TURQUOISE,
            Colors::PaleVioletRed => Bgr888::CSS_PALE_VIOLET_RED,
            Colors::PapayaWhip => Bgr888::CSS_PAPAYA_WHIP,
            Colors::PeachPuff => Bgr888::CSS_PEACH_PUFF,
            Colors::Peru => Bgr888::CSS_PERU,
            Colors::Pink => Bgr888::CSS_PINK,
            Colors::Plum => Bgr888::CSS_PLUM,
            Colors::PowderBlue => Bgr888::CSS_POWDER_BLUE,
            Colors::Purple => Bgr888::CSS_PURPLE,
            Colors::Red => Bgr888::CSS_RED,
            Colors::RosyBrown => Bgr888::CSS_ROSY_BROWN,
            Colors::RoyalBlue => Bgr888::CSS_ROYAL_BLUE,
            Colors::SaddleBrown => Bgr888::CSS_SADDLE_BROWN,
            Colors::Salmon => Bgr888::CSS_SALMON,
            Colors::SandyBrown => Bgr888::CSS_SANDY_BROWN,
            Colors::SeaGreen => Bgr888::CSS_SEA_GREEN,
            Colors::Seashell => Bgr888::CSS_SEASHELL,
            Colors::Sienna => Bgr888::CSS_SIENNA,
            Colors::Silver => Bgr888::CSS_SILVER,
            Colors::SkyBlue => Bgr888::CSS_SKY_BLUE,
            Colors::SlateBlue => Bgr888::CSS_SLATE_BLUE,
            Colors::SlateGray => Bgr888::CSS_SLATE_GRAY,
            Colors::Snow => Bgr888::CSS_SNOW,
            Colors::SpringGreen => Bgr888::CSS_SPRING_GREEN,
            Colors::SteelBlue => Bgr888::CSS_STEEL_BLUE,
            Colors::Tan => Bgr888::CSS_TAN,
            Colors::Teal => Bgr888::CSS_TEAL,
            Colors::Thistle => Bgr888::CSS_THISTLE,
            Colors::Tomato => Bgr888::CSS_TOMATO,
            Colors::Turquoise => Bgr888::CSS_TURQUOISE,
            Colors::Violet => Bgr888::CSS_VIOLET,
            Colors::Wheat => Bgr888::CSS_WHEAT,
            Colors::White => Bgr888::CSS_WHITE,
            Colors::WhiteSmoke => Bgr888::CSS_WHITE_SMOKE,
            Colors::Yellow => Bgr888::CSS_YELLOW,
            Colors::YellowGreen => Bgr888::CSS_YELLOW_GREEN,
        }
    }
}

impl From<Colors> for Rgb888 {
    fn from(val: Colors) -> Self {
        match val {
            Colors::AliceBlue => Rgb888::CSS_ALICE_BLUE,
            Colors::AntiqueWhite => Rgb888::CSS_ANTIQUE_WHITE,
            Colors::Aqua => Rgb888::CSS_AQUA,
            Colors::Aquamarine => Rgb888::CSS_AQUAMARINE,
            Colors::Azure => Rgb888::CSS_AZURE,
            Colors::Beige => Rgb888::CSS_BEIGE,
            Colors::Bisque => Rgb888::CSS_BISQUE,
            Colors::Black => Rgb888::CSS_BLACK,
            Colors::BlanchedAlmond => Rgb888::CSS_BLANCHED_ALMOND,
            Colors::Blue => Rgb888::CSS_BLUE,
            Colors::BlueViolet => Rgb888::CSS_BLUE_VIOLET,
            Colors::Brown => Rgb888::CSS_BROWN,
            Colors::BurlyWood => Rgb888::CSS_BURLY_WOOD,
            Colors::CadetBlue => Rgb888::CSS_CADET_BLUE,
            Colors::Chartreuse => Rgb888::CSS_CHARTREUSE,
            Colors::Chocolate => Rgb888::CSS_CHOCOLATE,
            Colors::Coral => Rgb888::CSS_CORAL,
            Colors::CornflowerBlue => Rgb888::CSS_CORNFLOWER_BLUE,
            Colors::Cornsilk => Rgb888::CSS_CORNSILK,
            Colors::Crimson => Rgb888::CSS_CRIMSON,
            Colors::Cyan => Rgb888::CSS_CYAN,
            Colors::DarkBlue => Rgb888::CSS_DARK_BLUE,
            Colors::DarkCyan => Rgb888::CSS_DARK_CYAN,
            Colors::DarkGoldenrod => Rgb888::CSS_DARK_GOLDENROD,
            Colors::DarkGray => Rgb888::CSS_DARK_GRAY,
            Colors::DarkGreen => Rgb888::CSS_DARK_GREEN,
            Colors::DarkKhaki => Rgb888::CSS_DARK_KHAKI,
            Colors::DarkMagenta => Rgb888::CSS_DARK_MAGENTA,
            Colors::DarkOliveGreen => Rgb888::CSS_DARK_OLIVE_GREEN,
            Colors::DarkOrange => Rgb888::CSS_DARK_ORANGE,
            Colors::DarkOrchid => Rgb888::CSS_DARK_ORCHID,
            Colors::DarkRed => Rgb888::CSS_DARK_RED,
            Colors::DarkSalmon => Rgb888::CSS_DARK_SALMON,
            Colors::DarkSeaGreen => Rgb888::CSS_DARK_SEA_GREEN,
            Colors::DarkSlateBlue => Rgb888::CSS_DARK_SLATE_BLUE,
            Colors::DarkSlateGray => Rgb888::CSS_DARK_SLATE_GRAY,
            Colors::DarkTurquoise => Rgb888::CSS_DARK_TURQUOISE,
            Colors::DarkViolet => Rgb888::CSS_DARK_VIOLET,
            Colors::DeepPink => Rgb888::CSS_DEEP_PINK,
            Colors::DeepSkyBlue => Rgb888::CSS_DEEP_SKY_BLUE,
            Colors::DimGray => Rgb888::CSS_DIM_GRAY,
            Colors::DodgerBlue => Rgb888::CSS_DODGER_BLUE,
            Colors::FireBrick => Rgb888::CSS_FIRE_BRICK,
            Colors::FloralWhite => Rgb888::CSS_FLORAL_WHITE,
            Colors::ForestGreen => Rgb888::CSS_FOREST_GREEN,
            Colors::Gainsboro => Rgb888::CSS_GAINSBORO,
            Colors::GhostWhite => Rgb888::CSS_GHOST_WHITE,
            Colors::Gold => Rgb888::CSS_GOLD,
            Colors::Goldenrod => Rgb888::CSS_GOLDENROD,
            Colors::Gray => Rgb888::CSS_GRAY,
            Colors::Green => Rgb888::CSS_GREEN,
            Colors::GreenYellow => Rgb888::CSS_GREEN_YELLOW,
            Colors::Honeydew => Rgb888::CSS_HONEYDEW,
            Colors::HotPink => Rgb888::CSS_HOT_PINK,
            Colors::IndianRed => Rgb888::CSS_INDIAN_RED,
            Colors::Indigo => Rgb888::CSS_INDIGO,
            Colors::Ivory => Rgb888::CSS_IVORY,
            Colors::Khaki => Rgb888::CSS_KHAKI,
            Colors::Lavender => Rgb888::CSS_LAVENDER,
            Colors::LavenderBlush => Rgb888::CSS_LAVENDER_BLUSH,
            Colors::LawnGreen => Rgb888::CSS_LAWN_GREEN,
            Colors::LemonChiffon => Rgb888::CSS_LEMON_CHIFFON,
            Colors::LightBlue => Rgb888::CSS_LIGHT_BLUE,
            Colors::LightCoral => Rgb888::CSS_LIGHT_CORAL,
            Colors::LightCyan => Rgb888::CSS_LIGHT_CYAN,
            Colors::LightGoldenrodYellow => Rgb888::CSS_LIGHT_GOLDENROD_YELLOW,
            Colors::LightGray => Rgb888::CSS_LIGHT_GRAY,
            Colors::LightGreen => Rgb888::CSS_LIGHT_GREEN,
            Colors::LightPink => Rgb888::CSS_LIGHT_PINK,
            Colors::LightSalmon => Rgb888::CSS_LIGHT_SALMON,
            Colors::LightSeaGreen => Rgb888::CSS_LIGHT_SEA_GREEN,
            Colors::LightSkyBlue => Rgb888::CSS_LIGHT_SKY_BLUE,
            Colors::LightSlateGray => Rgb888::CSS_LIGHT_SLATE_GRAY,
            Colors::LightSteelBlue => Rgb888::CSS_LIGHT_STEEL_BLUE,
            Colors::LightYellow => Rgb888::CSS_LIGHT_YELLOW,
            Colors::Lime => Rgb888::CSS_LIME,
            Colors::LimeGreen => Rgb888::CSS_LIME_GREEN,
            Colors::Linen => Rgb888::CSS_LINEN,
            Colors::Magenta => Rgb888::CSS_MAGENTA,
            Colors::Maroon => Rgb888::CSS_MAROON,
            Colors::MediumAquamarine => Rgb888::CSS_MEDIUM_AQUAMARINE,
            Colors::MediumBlue => Rgb888::CSS_MEDIUM_BLUE,
            Colors::MediumOrchid => Rgb888::CSS_MEDIUM_ORCHID,
            Colors::MediumPurple => Rgb888::CSS_MEDIUM_PURPLE,
            Colors::MediumSeaGreen => Rgb888::CSS_MEDIUM_SEA_GREEN,
            Colors::MediumSlateBlue => Rgb888::CSS_MEDIUM_SLATE_BLUE,
            Colors::MediumSpringGreen => Rgb888::CSS_MEDIUM_SPRING_GREEN,
            Colors::MediumTurquoise => Rgb888::CSS_MEDIUM_TURQUOISE,
            Colors::MediumVioletRed => Rgb888::CSS_MEDIUM_VIOLET_RED,
            Colors::MidnightBlue => Rgb888::CSS_MIDNIGHT_BLUE,
            Colors::MintCream => Rgb888::CSS_MINT_CREAM,
            Colors::MistyRose => Rgb888::CSS_MISTY_ROSE,
            Colors::Moccasin => Rgb888::CSS_MOCCASIN,
            Colors::NavajoWhite => Rgb888::CSS_NAVAJO_WHITE,
            Colors::Navy => Rgb888::CSS_NAVY,
            Colors::OldLace => Rgb888::CSS_OLD_LACE,
            Colors::Olive => Rgb888::CSS_OLIVE,
            Colors::OliveDrab => Rgb888::CSS_OLIVE_DRAB,
            Colors::Orange => Rgb888::CSS_ORANGE,
            Colors::OrangeRed => Rgb888::CSS_ORANGE_RED,
            Colors::Orchid => Rgb888::CSS_ORCHID,
            Colors::PaleGoldenrod => Rgb888::CSS_PALE_GOLDENROD,
            Colors::PaleGreen => Rgb888::CSS_PALE_GREEN,
            Colors::PaleTurquoise => Rgb888::CSS_PALE_TURQUOISE,
            Colors::PaleVioletRed => Rgb888::CSS_PALE_VIOLET_RED,
            Colors::PapayaWhip => Rgb888::CSS_PAPAYA_WHIP,
            Colors::PeachPuff => Rgb888::CSS_PEACH_PUFF,
            Colors::Peru => Rgb888::CSS_PERU,
            Colors::Pink => Rgb888::CSS_PINK,
            Colors::Plum => Rgb888::CSS_PLUM,
            Colors::PowderBlue => Rgb888::CSS_POWDER_BLUE,
            Colors::Purple => Rgb888::CSS_PURPLE,
            Colors::Red => Rgb888::CSS_RED,
            Colors::RosyBrown => Rgb888::CSS_ROSY_BROWN,
            Colors::RoyalBlue => Rgb888::CSS_ROYAL_BLUE,
            Colors::SaddleBrown => Rgb888::CSS_SADDLE_BROWN,
            Colors::Salmon => Rgb888::CSS_SALMON,
            Colors::SandyBrown => Rgb888::CSS_SANDY_BROWN,
            Colors::SeaGreen => Rgb888::CSS_SEA_GREEN,
            Colors::Seashell => Rgb888::CSS_SEASHELL,
            Colors::Sienna => Rgb888::CSS_SIENNA,
            Colors::Silver => Rgb888::CSS_SILVER,
            Colors::SkyBlue => Rgb888::CSS_SKY_BLUE,
            Colors::SlateBlue => Rgb888::CSS_SLATE_BLUE,
            Colors::SlateGray => Rgb888::CSS_SLATE_GRAY,
            Colors::Snow => Rgb888::CSS_SNOW,
            Colors::SpringGreen => Rgb888::CSS_SPRING_GREEN,
            Colors::SteelBlue => Rgb888::CSS_STEEL_BLUE,
            Colors::Tan => Rgb888::CSS_TAN,
            Colors::Teal => Rgb888::CSS_TEAL,
            Colors::Thistle => Rgb888::CSS_THISTLE,
            Colors::Tomato => Rgb888::CSS_TOMATO,
            Colors::Turquoise => Rgb888::CSS_TURQUOISE,
            Colors::Violet => Rgb888::CSS_VIOLET,
            Colors::Wheat => Rgb888::CSS_WHEAT,
            Colors::White => Rgb888::CSS_WHITE,
            Colors::WhiteSmoke => Rgb888::CSS_WHITE_SMOKE,
            Colors::Yellow => Rgb888::CSS_YELLOW,
            Colors::YellowGreen => Rgb888::CSS_YELLOW_GREEN,
        }
    }
}
