# For the sequence
color_names = [
    'Black',
    'DimGray',
    'Gray',
    'DarkGray',
    'Silver',
    'LightGray',
    'Gainsboro',
    'WhiteSmoke',
    'White',

    'DarkSlateGray',
    'SlateGray',
    'LightSlateGray',
    'LightSteelBlue',
    'Lavender',
    'FloralWhite',
    'AliceBlue',
    'GhostWhite',
    'Honeydew',
    'Ivory',
    'Azure',
    'Snow',

    'Maroon',
    'DarkRed',
    'Brown',
    'FireBrick',
    'Crimson',
    'Red',
    'Tomato',
    'Coral',
    'IndianRed',
    'LightCoral',
    'DarkSalmon',
    'Salmon',
    'LightSalmon',
    'OrangeRed',
    'DarkOrange',
    'Orange',
    'Gold',
    'DarkGoldenrod',
    'Goldenrod',
    'PaleGoldenrod',
    'DarkKhaki',
    'Khaki',
    'Olive',
    'Yellow',
    'YellowGreen',
    'DarkOliveGreen',
    'OliveDrab',
    'LawnGreen',
    'Chartreuse',
    'GreenYellow',
    'DarkGreen',
    'Green',
    'ForestGreen',
    'Lime',
    'LimeGreen',
    'LightGreen',
    'PaleGreen',
    'DarkSeaGreen',
    'MediumSpringGreen',
    'SpringGreen',
    'SeaGreen',
    'MediumAquamarine',
    'MediumSeaGreen',
    'LightSeaGreen',
    'Teal',
    'DarkCyan',
    'Aqua',
    'Cyan',
    'LightCyan',
    'DarkTurquoise',
    'Turquoise',
    'MediumTurquoise',
    'PaleTurquoise',
    'Aquamarine',
    'PowderBlue',
    'CadetBlue',
    'SteelBlue',
    'CornflowerBlue',
    'DeepSkyBlue',
    'DodgerBlue',
    'LightBlue',
    'SkyBlue',
    'LightSkyBlue',
    'MidnightBlue',
    'Navy',
    'DarkBlue',
    'MediumBlue',
    'Blue',
    'RoyalBlue',
    'BlueViolet',
    'Indigo',
    'DarkSlateBlue',
    'SlateBlue',
    'MediumSlateBlue',
    'MediumPurple',
    'DarkMagenta',
    'DarkViolet',
    'DarkOrchid',
    'MediumOrchid',
    'Purple',
    'Thistle',
    'Plum',
    'Violet',
    'Magenta',
    'Orchid',
    'MediumVioletRed',
    'PaleVioletRed',
    'DeepPink',
    'HotPink',
    'LightPink',
    'Pink',
    'AntiqueWhite',
    'Beige',
    'Bisque',
    'BlanchedAlmond',
    'Wheat',
    'Cornsilk',
    'LemonChiffon',
    'LightGoldenrodYellow',
    'LightYellow',
    'SaddleBrown',
    'Sienna',
    'Chocolate',
    'Peru',
    'SandyBrown',
    'BurlyWood',
    'Tan',
    'RosyBrown',
    'Moccasin',
    'NavajoWhite',
    'PeachPuff',
    'MistyRose',
    'LavenderBlush',
    'Linen',
    'OldLace',
    'PapayaWhip',
    'Seashell',
    'MintCream',
]

HTML_TEMPLATE = '''<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Webcolors</title>
    <style>
      h1 {font-family:sans-serif}
      table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
      }

      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
      }

      tr:nth-child(even) {
        background-color: #dddddd;
      }
    </style>
  </head>
  <body>
    <header>
      <h1>WebColors</h1>
    </header>
    <table class="dtable">
      <thead>
        <tr>
          <th>Color</th>
          <th>Color Name</th>
          <th>RGB</th>
        </tr>
      </thead>
      <tbody>
@@@
      </tbody>
    </table>
  </body>
</html>
'''

COLORS8_TEMPLATE = """// generated by create_corlors.py

#[repr(u8)]
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug)]
pub enum Colors {
@colors@}

const MAX: u8 = @col_cnt-1@;

use embedded_graphics::pixelcolor::{raw::RawU8, PixelColor};

impl PixelColor for Colors {
    type Raw = RawU8;
}

impl From<Colors> for RawU8 {
    fn from(color: Colors) -> RawU8 {
        RawU8::new(color as u8)
    }
}

use embedded_graphics::pixelcolor::{Bgr888, BinaryColor, Rgb888};
use embedded_graphics::prelude::WebColors;

impl From<Bgr888> for Colors {
    fn from(_color: Bgr888) -> Self {
        Colors::White
    }
}

impl From<Rgb888> for Colors {
    fn from(_color: Rgb888) -> Self {
        Colors::White
    }
}

impl From<BinaryColor> for Colors {
    fn from(_: BinaryColor) -> Self {
        Colors::White
    }
}

impl From<u8> for Colors {
    fn from(color: u8) -> Self {
        if color <= MAX {
            // Safety: We checked the range, so transmute is ok
            unsafe { core::mem::transmute::<u8, Colors>(color) }
        } else {
            Colors::Red // default Value to see something
        }
    }
}

impl From<Colors> for Bgr888 {
    fn from(val: Colors) -> Self {
        match val {
@bgr888_colors@        }
    }
}

impl From<Colors> for Rgb888 {
    fn from(val: Colors) -> Self {
        match val {
@rgb888_colors@        }
    }
}
"""

COLORS16_TEMPLATE = """// generated by create_corlors.py

#[repr(u16)]
#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash, Debug, Default)]
pub enum Colors {
@colors@}

use embedded_graphics::pixelcolor::{raw::RawU16, PixelColor};

impl PixelColor for Colors {
    type Raw = RawU16;
}

impl From<Colors> for RawU16 {
    fn from(color: Colors) -> RawU16 {
        RawU16::new(color as u16)
    }
}

use embedded_graphics::pixelcolor::{Bgr888, BinaryColor, Rgb888};
use embedded_graphics::prelude::WebColors;

impl From<Bgr888> for Colors {
    fn from(_color: Bgr888) -> Self {
        Colors::White
    }
}

impl From<Rgb888> for Colors {
    fn from(_color: Rgb888) -> Self {
        Colors::White
    }
}

impl From<BinaryColor> for Colors {
    fn from(_: BinaryColor) -> Self {
        Colors::White
    }
}

impl Colors {
    pub unsafe fn from_u16_unchecked(color: u16) -> Colors {
        // Safety: Every u16 is a valid Color
        unsafe { core::mem::transmute::<u16, Colors>(color) }
    }
}

impl From<Colors> for Bgr888 {
    fn from(val: Colors) -> Self {
        match val {
@bgr888_colors@        }
    }
}

impl From<Colors> for Rgb888 {
    fn from(val: Colors) -> Self {
        match val {
@rgb888_colors@        }
    }
}
"""

COOLORS565_TEMPLATE = """// generated by create_corlors.py

#[allow(dead_code)]
pub const RGB565_COLORS: [u16; @col_cnt@] = [
@colors565@];
"""

CLUT_COLORS_TEMPLATE = """// generated by create_colors.py

pub const CLUT_COLORS: [u32; 139] = [
@clut_colors@];
"""

# from webcolors import CSS3_NAMES_TO_HEX as color_dict
from webcolors import name_to_rgb, name_to_hex, names

color_dict = {}
for color_name in names("css3"):
    color_dict[color_name] = name_to_hex(color_name) 

def rgb565(r, g, b):
    # r, g, b values from 0..255
    r5 = int(r*32/256)
    g6 = int(g*64/256)
    b5 = int(b*32/256)
    return (r5 << 11) + (g6 << 5) + b5


def color_name_to_css_name(name):
    r = 'CSS_' + name[0]
    for c in name[1:]:
        if c.isupper():
            r += '_' + c
        else:
            r += c.upper()
    return r


path = "core/src/utils/colors8.rs"
with open(path, "w") as f:
    colors = ''
    for idx, color_name in enumerate(sorted(color_names)):
        rgb = name_to_rgb(color_name.lower())
        colorDesc = f"// Rgb({rgb.red}, {rgb.green}, {rgb.blue})"
        color = color_name + f" = {idx},"
        colors += f"    {color:27}{colorDesc}\n"

    rgb888_colors = ''        
    for color_name in sorted(color_names):
        css_color_name = color_name_to_css_name(color_name)
        rgb888_colors += f"            Colors::{color_name} => Rgb888::{css_color_name},\n"

    bgr888_colors = ''        
    for color_name in sorted(color_names):
        css_color_name = color_name_to_css_name(color_name)
        bgr888_colors += f"            Colors::{color_name} => Bgr888::{css_color_name},\n"

    col_cnt_1 = str(len(color_names) - 1)

    f.write(
        COLORS8_TEMPLATE
            .replace('@colors@', colors)
            .replace('@bgr888_colors@', bgr888_colors)
            .replace('@rgb888_colors@', rgb888_colors)
            .replace('@col_cnt-1@', col_cnt_1)
    )

EXCEPTIONS = {
    'Aqua': 0x07fe,
    'MintCream': rgb565(245, 247, 250),
    'Chartreuse': 0x7fe1,
    'GhostWhite': rgb565(248, 247, 255),
}
print("create_colors.py")
print(f"  Path '{path} created")


path = "core/src/utils/colors16.rs"
with open(path, "w") as f:
    colors = ''
    rgb888_colors = ''
    bgr888_colors = ''
    for idx, color_name in enumerate(sorted(color_names)):
        rgb = name_to_rgb(color_name.lower())
        colorDesc = f"// Rgb({rgb.red}, {rgb.green}, {rgb.blue})"
        if color_name in EXCEPTIONS:
            col565 = EXCEPTIONS[color_name]
        else:
            col565 = rgb565(rgb.red, rgb.green, rgb.blue)
        color = color_name + f" = 0x{col565:04x},"
        if color_name == "Red":
            colors += "    #[default]\n"
        colors += f"    {color:30} {colorDesc}\n"

        css_color_name = color_name_to_css_name(color_name)
        bgr888_colors += f"            Colors::{color_name} => Bgr888::{css_color_name},\n"
        rgb888_colors += f"            Colors::{color_name} => Rgb888::{css_color_name},\n"

    col_cnt_1 = str(len(color_names) - 1)

    f.write(
        COLORS16_TEMPLATE
            .replace('@colors@', colors)
            .replace('@col_cnt-1@', col_cnt_1)
            .replace('@bgr888_colors@', bgr888_colors)
            .replace('@rgb888_colors@', rgb888_colors)
    )
print(f"  Path '{path} created")

path = "core/src/utils/rgb565_colors.rs"
with open(path, "w") as f:    
    rgb888_colors = ''        
    for color_name in sorted(color_names):
        css_color_name = color_name_to_css_name(color_name)
        rgb888_colors += f"            Colors::{color_name} => Rgb888::{css_color_name},\n"


    col_cnt = str(len(color_names))

    colors565 = ''
    for idx, colorName in enumerate(sorted(color_names)):
        rgb = name_to_rgb(colorName.lower())
        converted = rgb565(rgb.red, rgb.green, rgb.blue)
        color = f"0x{converted:04x}, "
        colorDesc = f"// {idx:3} {colorName} RGB({rgb.red}, {rgb.green}, {rgb.blue})"
        colors565 += f"    {color}{colorDesc}\n"

    f.write(
        COOLORS565_TEMPLATE
            .replace('@col_cnt@', col_cnt)
            .replace('@colors565@', colors565)
    )
print(f"  Path '{path} created")

path = 'assets/colors.html'
with open(path, 'w') as f:
    content = ''
    for col in color_names:
        rgb = name_to_rgb(col)
        rgb_desc = f"Rgb({rgb.red}, {rgb.green}, {rgb.blue})"
        hex_desc = name_to_hex(col)
        content += f'        <tr>\n'
        content += f'          <td style="background: {hex_desc};">&nbsp;</td>\n'
        content += f'          <td>{col}</td>\n'
        content += f'          <td>{rgb_desc}</td>\n'
        content += f'        </tr>\n'
    f.write(
        HTML_TEMPLATE
            .replace('@@@', content)
    )
print(f"  Path '{path} created")

path = 'device/larus_frontend_v2/examples/driver/clut_colors.rs'
with open(path, 'w') as f:
    clut_colors = ''
    for idx, color_name in enumerate(sorted(color_names)):
        hex_str = name_to_hex(color_name).replace('#', '')
        clut_colors += f"    0x{idx:02x}{hex_str}, // {color_name}\n"

    f.write(
        CLUT_COLORS_TEMPLATE
            .replace('@clut_colors@', clut_colors)
    )
print(f"  Path '{path} created")
